import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { NavBar } from "./ui/NavBar";

const poppins = Poppins({ subsets: ['latin'], weight: ['300', '400', '600'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-[#fff] antialiased`}>
        {children}
        <NavBar className={poppins.className}></NavBar>
      </body>
    </html>
  );
}
